[tools]
hugo = "0.145.0"
"ubi:kaaveland/thumper" = "latest"

[tasks.build]
description = "Build the blog pages"
run = "hugo"

[tasks.clean]
description = "Clean the slate"
run = "rm -rf public"

[tasks.deploy]
description = "Deploy the blog pages"
depends = ["clean", "build"]
run = "thumper sync public kaveland --ignore eugene --verbose && thumper purge-zone kaveland"
