[tools]
hugo = "0.145.0"
"ubi:kaaveland/bunnysync" = "latest"

[tasks.build]
description = "Build the blog pages"
run = "hugo"

[tasks.clean]
description = "Clean the slate"
run = "rm -rf public"

[tasks.deploy]
description = "Deploy the blog pages"
depends = ["clean", "build"]
run = "bunnysync sync public kaveland --ignore eugene --verbose && bunnysync purge-zone kaveland"
