[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Robin Kåveland", email = "kaaveland@gmail.com"},
]
dependencies = [
    "pelican[markdown]>=4.8.0",
    "ghp-import>=2.1.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}

